/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NavbarConfig {
  /**
   * List of links to show in the navigation bar
   */
  links: {
    /**
     * Display string for the link
     */
    title: string;
    /**
     * Page to link to
     */
    href: string;
  }[];
  [k: string]: unknown;
}
