/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RaceImageTag = "logo" | "thumb";

export interface RaceInfo {
  /**
   * Basic race information
   */
  info: {
    name: {
      native: string;
      translated: string;
    };
    grade: "g1" | "g2" | "g3";
    trackInfo?: {
      trackName: string;
      distance: number;
      trackType: "turf" | "dirt";
      direction: "cw" | "ccw";
    };
    raceInfo?: {
      /**
       * Sortable number based on how late in the year the race usually is. Month + decimal.
       */
      raceTimeValue?: number;
      /**
       * Readable description for when the race usually takes place.
       */
      raceTimeDescription?: string;
      startYear?: number;
      previousNames?: {
        name: string;
        untilYear: number;
      }[];
    };
    history?: {
      year: number;
      characters: {
        characterId: string;
        place: number;
      }[];
    }[];
    links?: {
      wikipediaUrlJP?: string;
      wikipediaUrlEN?: string;
    };
  };
  /**
   * List of relevant images
   */
  images: {
    tag: RaceImageTag;
    /**
     * File path to the image relative to the /public/images folder
     */
    file: string;
  }[];
  [k: string]: unknown;
}
